added few links to operating system resources
vicky002/AlgoWiki pull request #161
Opened 2017-10-20 05:41 UTC by Yathartha22

added few links in reference to #111

2017-10-20 05:46 UTC, vicky002 requested changes

2017-10-20 05:46 UTC, vicky002 commented on Operating System/sources.md
> +- http://www.studytonight.com/operating-system/introduction-operating-systems
It will be good to have names rather than just pasting links directly. 

make it something like 

[Studytonight: Operating System](http://www.studytonight.com/operating-system/introduction-operating-systems) [Article]
.... [Book]
...  [Course]

2017-10-20 05:54 UTC, Yathartha22 commented on Operating System/sources.md
> +- http://www.studytonight.com/operating-system/introduction-operating-systems
okay, I thought since the above are just links I should rather add simple links 😄, but no problem I will make the changes.

2017-10-20 06:12 UTC, Yathartha22 commented
I thought to create sections for PPT resources and article resource(rather than links directly).
Hope this looks better!

2017-10-27 15:50 UTC, vicky002 approved these changes

2017-10-27 15:51 UTC, vicky002 commented
@Yathartha22 seems like there is small conflict.

2017-10-28 01:51 UTC, merged