Added some changes
vicky002/AlgoWiki pull request #240
Opened 2018-10-03 19:32 UTC by nsrivastava645

2 pdfs and 2 links to tutorials

2018-10-04 09:14 UTC, Byte7 requested changes

2018-10-04 09:14 UTC, Byte7 commented on R/resources.md
> +* [HandsOn Programming with R](https://d1b10bmlvqabco.cloudfront.net/attach/ighbo26t3ua52t/igp9099yy4v10/igz7vp4w5su9/OReilly_HandsOn_Programming_with_R_2014.pdf)
The books are paid ones. Please remove them. Rest of the links look fine, I'll merge them after these changes.

2020-06-12 06:10 UTC, codingonHP commented on R/resources.md
> +* [HandsOn Programming with R](https://d1b10bmlvqabco.cloudfront.net/attach/ighbo26t3ua52t/igp9099yy4v10/igz7vp4w5su9/OReilly_HandsOn_Programming_with_R_2014.pdf)
I resolved this.

2020-06-12 06:11 UTC, codingonHP commented
Closing this PR as now we are tracking this as part of https://github.com/vicky002/AlgoWiki/pull/341 after resolving the conflicts.

2020-06-12 06:11 UTC, closed without merging