Added and fixed links in Competitive-Programming.md
vicky002/AlgoWiki pull request #243
Opened 2018-10-03 20:11 UTC by agrocks23

2018-10-04 19:22 UTC, Byte7 requested changes

2018-10-04 19:22 UTC, Byte7 commented on Competitive-Programming/Competitive-Programming.md
> +* [Competitive Programming (3rd ed.)](https://drive.google.com/open?id=1Ld1Z7y0di4DTWgF-sqlJd-5AMAdtxXaW)
Hi @agrocks23 The third edition of CP book is paid one. So, we cannot add this to the change. Rest of the stuff looks fine. Please revert this back. Also, pull the new changes and then branch out and push. This will help in resolving merge conflicts.

2020-06-12 06:04 UTC, codingonHP commented
@agrocks23 Please have a look when you get time so that we can merge and close this PR.
Thanks for your contribution :)

2020-06-12 06:43 UTC, agrocks23 commented
@codingonHP Please go ahead and close this PR. Not working on this anymore.

2020-06-12 06:43 UTC, closed without merging