Added React Video and Books
vicky002/AlgoWiki pull request #322
Opened 2019-10-08 17:45 UTC by PS-Ddevil

Added Learning React: Functional Web Development with React and Redux, React: Up & Running: Building Web Applications, The Road to Learn React: Your Journey to Master Plain Yet Pragmatic React.Js and TheNetNinja youtube tutorial on react and redux.

2019-10-17 15:18 UTC, Byte7 requested changes

2019-10-17 15:18 UTC, Byte7 commented on JAVASCRIPT/resources.md
> +- [Learning React: Functional Web Development with React and Redux](http://www.r-5.org/files/books/computers/languages/escss/w-tkt/react/Alex_Banks_and_Eve_Porcello-Learning_React-EN.pdf) - Alex Bank
Hi @PS-Ddevil ,  These are paid books. We only collect unpaid and free lilnks and resources.

2019-10-17 16:01 UTC, PS-Ddevil commented on JAVASCRIPT/resources.md
> +- [Learning React: Functional Web Development with React and Redux](http://www.r-5.org/files/books/computers/languages/escss/w-tkt/react/Alex_Banks_and_Eve_Porcello-Learning_React-EN.pdf) - Alex Bank
@Byte7 Kindly see the modified commit

2019-10-19 04:06 UTC, Byte7 approved these changes
Nice work, Keep contributing!

2019-10-19 04:07 UTC, merged