added URL's for ML books
vicky002/AlgoWiki pull request #324
Opened 2019-10-11 01:36 UTC by designMoreWeb

Reinforcement Learning: An Introduction (Draft)
Machine Learning, Neural and Statistical Classification

2019-10-17 15:25 UTC, Byte7 requested changes

2019-10-17 15:25 UTC, Byte7 commented on Machine-Learning/Sources.md
> +* [Reinforcement Learning: An Introduction (Draft)](https://drive.google.com/file/d/1opPSz5AZ_kVa1uWOdOiveNiBFiEOHjkG/view)(PDF Book)
The reinforcement learning is a paid book. Please remove it.

2020-06-11 17:44 UTC, codingonHP commented
@designMoreWeb Please squash the commits :)

2020-06-12 05:42 UTC, codingonHP approved these changes

2021-08-22 13:51 UTC, Byte7 approved these changes

2021-08-22 13:52 UTC, merged