shell script topic added
vicky002/AlgoWiki pull request #61
Opened 2017-08-15 17:44 UTC by rushirg

I Have added the Shell-Script topic and a resource.md file.

Please let me know if the resource.md file is correct as per your format or if it needs any changes.

Thank you!

2017-09-17 04:34 UTC, vicky002 commented
Hey @rushirg, can you please add little more resources? 

I will merge quickly then. :+1:

2017-10-07 05:53 UTC, rushirg commented
Added cheat sheet, interview questions resources.
Thank you :+1:

2017-10-27 14:54 UTC, Yathartha22 requested changes

2017-10-27 14:54 UTC, Yathartha22 commented on Shell-Script/resource.md
> +* [Linux Shell Scripting Tutorial] (http://www.freeos.com/guides/lsst/)
Please remove space between brackets.
Also, change heading `Links ` to `Resource`, I guess it would be more appropriate.

2017-10-31 17:25 UTC, Yathartha22 requested changes

2017-10-31 17:25 UTC, Yathartha22 commented on Shell-Script/resource.md
> +<<<<<<< HEAD
Remove this.

2017-10-31 17:25 UTC, Yathartha22 commented on Shell-Script/resource.md
> +=======
Remove it.

2017-10-31 17:25 UTC, Yathartha22 commented on Shell-Script/resource.md
> +>>>>>>> 0500936da61a68a29f00d20c3611c92c6d8a6c00
Remove it.

2017-11-02 16:19 UTC, rushirg commented
@Yathartha22 Thank you, for your help. Please review the updated one too.

2017-11-02 16:42 UTC, Yathartha22 approved these changes

2017-11-02 16:45 UTC, Yathartha22 commented
Great work  :tada: @rushirg

2017-11-02 16:46 UTC, merged